### ISSUE TITLE
License

### ISSUE THREAD

**Issue by brandonkal** [nestybox/sysbox-external#38]
I'm not seeing any license in this repository.

**Comment by ctalledo** [comment]
Thanks for the reminder Brandon.

There is no source code in the repo, only the binaries for the software (it's proprietary currently).

However we do have some Dockerfiles which are free for anyone to use, and we will be adding a license for those very soon.

**Comment by rodnymolina** [comment]
Brandon, please feel free to use our software (binaries) for your personal use, it's free at this point. In terms of Licensing for our binaries, this is work-in-progress; we will have specific terms once we complete the associated EULA.

**Comment by ctalledo** [comment]
We've added the LICENSE file (MIT license) for the dockerfiles and scripts in this repo.
